version: "3.9"

services:
  nextjs:
    container_name: compose-nextjs-container
    build:
      context: nextjs
      dockerfile: Dockerfile
    image: cr.yandex/${CR_REGISTRY}/ntlstl-nextjs:latest
    # platform: linux/amd64
    networks:
      - internet
    ports:
      - 3000:3000
    restart: unless-stopped

  react:
    container_name: compose-react-container
    build:
      context: react
      dockerfile: Dockerfile
    image: cr.yandex/${CR_REGISTRY}/ntlstl-react:latest
    # platform: linux/amd64
    networks:
      - internet
    ports:
      - 5173:3000
    restart: unless-stopped

networks:
  internal-network:
    driver: bridge
    internal: true
  internet:
    driver: bridge